export const DATA_TYPE = {
  DATA_TYPE_FALSE: 0,
  DATA_TYPE_TRUE: 1,
  DATA_TYPE_UINT8: 2,
  DATA_TYPE_UINT16: 3,
  DATA_TYPE_UINT32: 4,
  DATA_TYPE_NUINT8: 5,
  DATA_TYPE_NUINT16: 6,
  DATA_TYPE_NUINT32: 7,
  DATA_TYPE_FLOAT32: 8,
  DATA_TYPE_STRING: 9,
  DATA_TYPE_UINT16_ARRAY: 10,
  DATA_TYPE_UINT32_ARRAY: 11,
  DATA_TYPE_FLOAT32_ARRAY: 12,
  DATA_TYPE_OBJECT: 13,
  DATA_TYPE_ARRAY: 14,
};

export default DATA_TYPE;
