import * as THREE from "three";
import {
  basicFragment,
  basicNeiQFragment,
  basicNeiQVertex,
  basicSilPopFragment,
  basicSilPopVertex,
  basicSparkleQFragment,
  basicSparkleQVertex,
  basicVertex,
  bezierParticleFragment,
  bezierParticleVertex,
  characterBaseFragment,
  characterBaseVertex,
  characterOutlineFragment,
  characterOutlineVertex,
  depthFragment,
  depthVertex,
  fxaaFragment,
  fxaaVertex,
  huohuoEffectFragment,
  huohuoEffectVertex,
  reflectFragment,
  reflectVertex,
} from "../shaders/index.js";

export const shaderSettings = {
  BASIC: new THREE.ShaderMaterial({
    vertexShader: basicVertex,
    fragmentShader: basicFragment,
    transparent: true,
    depthTest: true,
    depthWrite: true,
    side: THREE.FrontSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {
      opacity: { value: 1 },
      color: { value: new THREE.Color(16712000) },
    },
    defines: {
      USE_TEXTURE: 1,
      ALPHA_TEST: 0,
    },
  }),

  FXAA: new THREE.ShaderMaterial({
    vertexShader: fxaaVertex,
    fragmentShader: fxaaFragment,
    transparent: true,
    depthTest: false,
    depthWrite: false,
    side: THREE.FrontSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: { opacity: { value: 1 } },
    defines: {},
  }),

  CHARACTER_BASE: new THREE.ShaderMaterial({
    vertexShader: characterBaseVertex,
    fragmentShader: characterBaseFragment,
    transparent: true,
    depthTest: true,
    depthWrite: true,
    side: THREE.FrontSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {
      rimIntensity: { value: 0 },
      metalDarkColor: { value: new THREE.Color(11107953) },
      metalLightColor: { value: new THREE.Color(14405056) },
      metallness1: { value: 0 },
      metallness2: { value: 0 },
      metallness3: { value: 0 },
      metallness4: { value: 0 },
      metallness5: { value: 0 },
      shadowColor1: { value: new THREE.Vector4(0, 0, 0, 0) },
      shadowColor2: { value: new THREE.Vector4(0, 0, 0, 0) },
      shadowColor3: { value: new THREE.Vector4(0, 0, 0, 0) },
      shadowColor4: { value: new THREE.Vector4(0, 0, 0, 0) },
      shadowColor5: { value: new THREE.Vector4(0, 0, 0, 0) },
      shadowColor6: { value: new THREE.Vector4(0, 0, 0, 0) },
      shadowColor7: { value: new THREE.Vector4(0, 0, 0, 0) },
      shadowColor8: { value: new THREE.Vector4(0, 0, 0, 0) },
    },
    defines: {
      USE_LIGHTMAP: 1,
      USE_SHADOW_RAMP: 1,
      USE_MATMAP: 0,
      MAT_CHANNEL: 0,
      USE_METALMAP: 0,
      USE_FACEMAP: 0,
      USE_UV2: 0,
      USE_FADE: 0,
      USE_DEPTH: 0,
      USE_ALPHA: 0,
      USE_NEW_MAT: 0,
      USE_NORMAL2: 0,
      ALPHA_TEST: 0,
      HIDE_FLOWER: 0,
    },
  }),

  CHARACTER_OUTLINE: new THREE.ShaderMaterial({
    vertexShader: characterOutlineVertex,
    fragmentShader: characterOutlineFragment,
    transparent: true,
    depthTest: true,
    depthWrite: true,
    side: THREE.BackSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {
      strokeColor: { value: new THREE.Color(0) },
      strokeColor2: { value: new THREE.Color(0) },
      strokeColor3: { value: new THREE.Color(0) },
      strokeColor4: { value: new THREE.Color(0) },
      strokeColor5: { value: new THREE.Color(0) },
      strokeColor6: { value: new THREE.Color(0) },
      strokeColor7: { value: new THREE.Color(0) },
      opacity: { value: 1 },
    },
    defines: {
      MAT_CHANNEL: 0,
      DISCARD: 0,
      SIMPLE_MODE: 1,
      USE_DEPTH: 0,
      HIDE_FLOWER: 0,
    },
  }),

  REFLECT: new THREE.ShaderMaterial({
    vertexShader: reflectVertex,
    fragmentShader: reflectFragment,
    transparent: true,
    depthTest: true,
    depthWrite: true,
    side: THREE.FrontSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {},
    defines: {},
  }),

  DEPTH: new THREE.ShaderMaterial({
    vertexShader: depthVertex,
    fragmentShader: depthFragment,
    transparent: false,
    depthTest: true,
    depthWrite: true,
    side: THREE.FrontSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {},
    defines: { HIDE_FLOWER: 0 },
  }),

  BASIC_SIL_POP: new THREE.ShaderMaterial({
    vertexShader: basicSilPopVertex,
    fragmentShader: basicSilPopFragment,
    transparent: true,
    depthTest: true,
    depthWrite: true,
    side: THREE.FrontSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {
      opacity: { value: 1 },
      color: { value: new THREE.Color(16712000) },
    },
    defines: { USE_TEXTURE: 1, ALPHA_TEST: 0 },
  }),

  BEZIER_PARTICLE: new THREE.ShaderMaterial({
    vertexShader: bezierParticleVertex,
    fragmentShader: bezierParticleFragment,
    transparent: true,
    depthTest: true,
    depthWrite: false,
    side: THREE.DoubleSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {
      opacity: { value: 1 },
      lifeCurve: { value: 1 },
      size: { value: new THREE.Vector2(20, 30) },
      speed: { value: new THREE.Vector2(0.5, 1) },
      alpha: { value: new THREE.Vector2(0.5, 1) },
      startMin: { value: new THREE.Vector3(-500, -500, -500) },
      startMax: { value: new THREE.Vector3(500, 500, 500) },
      ctrMin: { value: new THREE.Vector3(0, 0, 0) },
      ctrMax: { value: new THREE.Vector3(0, 0, 0) },
      endMin: { value: new THREE.Vector3(0, 0, 0) },
      endMax: { value: new THREE.Vector3(0, 0, 0) },
      freqMin: { value: new THREE.Vector3(1, 1, 1) },
      freqMax: { value: new THREE.Vector3(1, 1, 1) },
      ampMin: { value: new THREE.Vector3(0, 0, 0) },
      ampMax: { value: new THREE.Vector3(0, 0, 0) },
      delayMin: { value: new THREE.Vector3(0, 0, 0) },
      delayMax: { value: new THREE.Vector3(6.28, 6.28, 6.28) },
      tailLen: { value: 1 },
      scale: { value: new THREE.Vector2(1, 1) },
      rotMin: { value: new THREE.Vector3(0, 0, 0) },
      rotMax: { value: new THREE.Vector3(0, 0, 0) },
      rotRnd: { value: new THREE.Vector2(0, 0) },
      gravityMin: { value: new THREE.Vector3(0, -200, 0) },
      gravityMax: { value: new THREE.Vector3(0, -500, 0) },
      blink: { value: new THREE.Vector3(0.2, 0.8, 5) },
      imgNum: { value: 1 },
      seed: { value: 0 },
    },
    defines: {
      DELTA_OFFSET: 0,
      USE_BEZIER: 2,
      USE_WIGGLE: 0,
      FOLLOW_PATH: 0,
      FOLLOW_SIZE: 0,
      USE_ROTATE: 0,
      USE_FADE: 0,
      USE_BLINK: 0,
      USE_GRAVITY: 0,
      USE_SCALE: 0,
      USE_SPRITE: 0,
      MULTI_IMGS: 0,
      LOOP_COUNT: 0,
    },
  }),

  HUOHUO_EFF: new THREE.ShaderMaterial({
    vertexShader: huohuoEffectVertex,
    fragmentShader: huohuoEffectFragment,
    transparent: true,
    depthTest: true,
    depthWrite: true,
    side: THREE.FrontSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {
      opacity: { value: 1 },
      color: { value: new THREE.Color(16712000) },
    },
    defines: { USE_TEXTURE: 1, ALPHA_TEST: 0 },
  }),

  BASIC_SPARKLE_Q: new THREE.ShaderMaterial({
    vertexShader: basicSparkleQVertex,
    fragmentShader: basicSparkleQFragment,
    transparent: true,
    depthTest: true,
    depthWrite: true,
    side: THREE.FrontSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {
      opacity: { value: 1 },
      color: { value: new THREE.Color(16712000) },
    },
    defines: { USE_TEXTURE: 1, ALPHA_TEST: 0 },
  }),

  BASIC_NEI_Q: new THREE.ShaderMaterial({
    vertexShader: basicNeiQVertex,
    fragmentShader: basicNeiQFragment,
    transparent: true,
    depthTest: true,
    depthWrite: true,
    side: THREE.FrontSide,
    blending: THREE.NormalBlending,
    lights: false,
    wireframe: false,
    extensions: { derivatives: false },
    uniforms: {
      opacity: { value: 1 },
      color: { value: new THREE.Color(16712000) },
    },
    defines: { USE_TEXTURE: 1, ALPHA_TEST: 0 },
  }),
};

export default shaderSettings;
